cloud:
  cloudflare:
    service:
      contentBucket:
        accessKey: ${CLOUD_CLOUDFLARE_CONTENT_BUCKET_ACCESS_KEY}
        secretKey: ${CLOUD_CLOUDFLARE_CONTENT_BUCKET_SECRET_KEY}
        endpoint: ${CLOUD_CLOUDFLARE_CONTENT_BUCKET_ENDPOINT}
        bucketPublicUrl: ${CLOUD_CLOUDFLARE_CONTENT_BUCKET_PUBLIC_URL}
        bucketName: ${CLOUD_CLOUDFLARE_CONTENT_BUCKET_NAME}
        imageContentStoragePath: images/
        imagePostContentPath: posts/
        imageCommentContentPath: post-comments/
        imageProfilePath: profiles/

  minio:
    service:
      videos:
        endpoint: ${CLOUD_MINIO_VIDEOS_BUCKET_ENDPOINT}
        access-key: ${CLOUD_MINIO_VIDEOS_BUCKET_ACCESS_KEY}
        secret-key: ${CLOUD_MINIO_VIDEOS_BUCKET_SECRET_KEY}
        bucket-name: ${CLOUD_MINIO_VIDEOS_BUCKET_NAME}
        hls-dir-path: hls/
        poster-dir-path: poster/
        bucketPublicUrl: https://media.feelog.net/
        m3u8-file-name: output.m3u8
