openapi:
  #  Vworld
  vworld:
    clientId: ${OPENAPI_VWORLD_CLIENT_ID}
    version: 2
    apiFormat: json
    crs: epsg:4326
    rspType: BOTH
    rspRoadType: ROAD
    addressServiceParam: address
    reverseGeocodeParam: getAddress
    geocodeParam: getcoord

  # 주소기반산업지원서비스
  businessjuso:
    secretKey: ${OPENAPI_BUSINESSJUSO_SECRET_KEY}
    apiFormat: json
    countPerPage: 20
    firstSort: none

  # 네이버 개발자 API
  naverdevelopers:
    xNaverClientId: ${OPENAPI_NAVERDEVELOPERS_CLIENT_ID}
    xNaverClientSecret: ${OPENAPI_NAVERDEVELOPERS_SECRET_KEY}
    mapLocalMaxSrchNum: 5

  # 카카오 개발자 API
  kakaodevelopers:
    restApi: ${OPENAPI_KAKAO_DEVELOPERS_REST_API}

  appledevelopers:
    appleSocialServiceClientId: com.feelog.social
    appleTeamId: 7HT428P8J4
    appleFeelogApiKeyId: 9KL5F392Y2
    appleFeelogApiPrivateKey: ${OPENAPI_APPLE_FEELOG_API_PRIVATE_KEY}
    appleMapApiKey: ${OPENAPI_APPLE_MAP_API_KEY}


  googledevelopers:
    oauthClientId: ${OPENAPI_GOOGLE_DEVELOPERS_OAUTH_CLIENT_ID}
    oauthClientSecret: ${OPENAPI_GOOGLE_DEVELOPERS_OAUTH_CLIENT_SECRET_KEY}



  # Discord
  discord:
    webhook:
      postReport:
        channelId: ${OPENAPI_DISCORD_WEBHOOK_PORT_REPORT_CHANNEL_ID}
        token: ${OPENAPI_DISCORD_WEBHOOK_PORT_REPORT_TOKEN}
      serviceNotification:
        channelId: ${OPENAPI_DISCORD_WEBHOOK_SERVICE_NOTIFICATION_WEBHOOK_CHANNEL_ID}
        token: ${OPENAPI_DISCORD_WEBHOOK_SERVICE_NOTIFICATION_WEBHOOK_TOKEN}
      serviceActivityLog:
        channelId: ${OPENAPI_DISCORD_WEBHOOK_SERVICE_ACTIVITY_LOG_WEBHOOK_CHANNEL_ID}
        token: ${OPENAPI_DISCORD_WEBHOOK_SERVICE_ACTIVITY_LOG_WEBHOOK_TOKEN}