server:
  port: ${PORT:8080}

logging:
  level:
    org:
      atmosphere: warn

spring:
  application:
    name: feelog-server

  mustache:
    check-template-location: false

  profiles:
    group:
      prod:
        - db
        - cloud
        - swagger
        - websocket
        - rabbitmq
        - redis
        - auth
        - openapi
        - vaadin
        - config
        - url

      local:
        - db-local
        - cloud
        - swagger
        - websocket
        - rabbitmq-local
        - redis-local
        - auth
        - openapi
        - vaadin
        - config-local
        - url