spring:
  flyway:
    enabled: true # Flyway 활성화
    locations: classpath:db/migration # 마이그레이션 파일 위치
    baseline-on-migrate: true # 이미 존재하는 DB에 baseline을 적용
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
    database: postgresql
    open-in-view: false

logging:
  level:
    org.springframework.jdbc.core: TRACE
