server:
  port: ${PORT:8080}

logging:
  level:
    org:
      atmosphere: warn

spring:
  application:
    name: feelog-server

  mustache:
    check-template-location: false

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7

  profiles:
    group:
      prod:
        - db
        - cloud
        - swagger
        - websocket
        - rabbitmq
        - redis
        - auth
        - openapi
        - vaadin
        - config
        - common

      local:
        - db-local
        - cloud-local
        - swagger-local
        - websocket
        - rabbitmq-local
        - redis-local
        - auth
        - openapi-local
        - vaadin
        - config-local
        - common-local