app-websocket:
  registry:
    endpoint: /ws
    fallback:
      heartbeatTime: 25000 # 25 second
    messagebroker:
      heartbeat:
        clientToServerTime: 60000 # 60 second
        serverToClientTime: 60000 # 60 second
      taskSchedular:
        poolSize: 10
        threadNamePrefix: websocket-task-
    application:
      config:
        maxTextMessageBufferSize: 16384 # 16kb
        maxBinaryMessageBufferSize: 3145728 # 3mb


