spring:
  flyway:
    enabled: true # Flyway 활성화
    locations: classpath:db/migration # 마이그레이션 파일 위치
    baseline-on-migrate: true # 이미 존재하는 DB에 baseline을 적용
    username: feelog_postgres_master
    password: TzBJwaxmVQR4I25Q75yhgtvSQezRxR2i

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/feelog_db?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: feelog_postgres_master
    password: TzBJwaxmVQR4I25Q75yhgtvSQezRxR2i

  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: validate
#    generate-ddl: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
    database: postgresql
    open-in-view: false

logging:
  level:
    org.springframework.jdbc.core: TRACE
