server:
  port: ${PORT:8080}

logging:
  level:
    org:
      atmosphere: warn

spring:
  application:
    name: feelog-server

  mustache:
    check-template-location: false

  profiles:
    active:
      - prod

    group:
      prod:
        - db
        - cloud
        - swagger
        - websocket
        - redis
        - auth
        - openapi
        - vaadin
        - config