name: Postvue API Server CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_USER: ${{ secrets.SERVER_REMOTE_USER }}
        REMOTE_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Deploy to server
      env:
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_USER: ${{ secrets.SERVER_REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.SERVER_REMOTE_PORT }}
        REMOTE_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        SERVICE_DIR: ${{ secrets.SERVICE_DIR }}
      run: |
        sshpass -p "${REMOTE_PASSWORD}" ssh -o StrictHostKeyChecking=no -p ${REMOTE_PORT} "${REMOTE_USER}@${REMOTE_HOST}" << EOF
          cd ${SERVICE_DIR}
          echo "Logging into Docker Hub..."
          echo "${DOCKER_HUB_ACCESS_TOKEN}" | docker login --username "${DOCKER_HUB_USERNAME}" --password-stdin
          echo "${REMOTE_PASSWORD}" | sudo -S docker-compose down --volumes --remove-orphans
          echo "${REMOTE_PASSWORD}" | sudo -S docker compose pull
          echo "${REMOTE_PASSWORD}" | sudo -S docker-compose up -d
        EOF

